---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: ansible-role-openssl
      openssl_items:
        - name: my_openssl_key
          common_name: my.example.com
